version: '3.9'

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    container_name: munibuddy_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    container_name: munibuddy_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: munibuddy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data: