version: '3.9'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    container_name: munibuddy_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - ./backend/gtfs_data:/app/app/gtfs_data:ro

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: ${VITE_API_BASE}
        VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
    env_file:
      - ./frontend/.env
    container_name: munibuddy_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  caddy:
    build:
      context: ./caddy
    container_name: munibuddy_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - frontend

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: munibuddy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_cache:
    image: redis:7.4.2
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./backend/redis.conf:/etc/redis/redis.conf
      - redis_data:/data
    environment:
      - REDIS_MAXMEMORY=256mb
    sysctls:
      - vm.overcommit_memory=1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
