services:
  - type: web
    name: munibuddy-backend
    env: docker
    repo: https://github.com/albertfast/MuniBuddy.git
    branch: main
    dockerfilePath: backend/dockerfile
    buildFilter:
      paths:
        - backend/**/*
        - docker-compose.yml
        - backend/gtfs_data/**/*
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        value: postgresql://myuser:mypassword@postgres_db:5432/munibuddy_db
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: 6379
      - key: API_KEY
        sync: false

  - type: web
    name: munibuddy-frontend
    env: docker
    repo: https://github.com/albertfast/MuniBuddy.git
    branch: main
    dockerfilePath: frontend/dockerfile
    buildFilter:
      paths:
        - frontend/**/*
    envVars:
      - key: VITE_API_URL
        value: https://munibuddy-backend.onrender.com
      - key: VITE_GOOGLE_MAPS_API_KEY
        sync: false

  - type: redis
    name: redis
    ipAllowList: []

  - type: pserv
    name: postgres_db
    env: docker
    plan: free